img_size: [120,160]
top_cutoff: 40

colors:
  RED:
    low_1: [0,30,100]
    high_1: [17,255,255]
    low_2: [165,40,100]
    high_2: [180,255,255]
  WHITE:
    low: [41,0,100]
    high: [164,100,255]
  YELLOW:
    low: [23,40,100]
    high: [40,255,255]

line_detector_parameters:
  canny_thresholds: [80,200]
  canny_aperture_size: 3
  dilation_kernel_size: 3
  hough_threshold: 2
  hough_min_line_length: 3
  hough_max_line_gap: 1
